# Generated by Django 5.1 on 2024-09-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pdf',
            new_name='PDF_Files',
        ),
    ]
