# Generated by Django 5.1 on 2024-09-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_rename_pdf_pdf_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF_Files',
            new_name='PDFFiles',
        ),
    ]
