# Generated by Django 5.1 on 2024-09-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_id', models.CharField(default='67d85663-1ee8-45a2-9756-7a2d3f827eb8', max_length=100)),
                ('client_name', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('misc_details', models.CharField(max_length=100)),
                ('payments_status', models.CharField(choices=[('Pending', 'pending'), ('Successful', 'successful')], max_length=50)),
                ('date_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
