# Generated by Django 5.1 on 2024-09-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transection_id',
            field=models.CharField(default='54e41f86-ddd6-4a4b-9d19-02c308ab9aa3', max_length=100),
        ),
    ]
