# Generated by Django 5.1 on 2024-09-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_transection_id_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='105469bb-9543-4aa4-b987-5c21bd8ac3ba', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payments_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Successful', 'successful')], default='Pending', max_length=50),
        ),
    ]
