# Generated by Django 5.1 on 2024-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='3ae3182a-76f4-484f-838c-5a46be29cb21', max_length=100),
        ),
    ]
