# Generated by Django 5.1 on 2024-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payments_status',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='fcbb141a-ed5d-4125-94d7-e6d509c8e563', max_length=100),
        ),
    ]
