# Generated by Django 5.1 on 2024-09-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='6b1c22c5-1578-4c3d-baed-d7179aa94b59', max_length=100),
        ),
    ]
