# Generated by Django 5.1 on 2024-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='83f37578-4909-4914-b052-f27a023d3a71', max_length=100),
        ),
    ]
