# Generated by Django 5.1 on 2024-09-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='f273da75-dee2-42e8-954c-c7225f4d86b4', max_length=100),
        ),
    ]
