# Generated by Django 5.1 on 2024-09-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='0335b317-20e9-4813-9047-a9c38cdabaf8', max_length=100),
        ),
    ]
