# Generated by Django 5.1 on 2024-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='199ca09a-8e9f-49f1-926d-11d964b17289', max_length=100),
        ),
    ]
