# Generated by Django 5.1 on 2024-10-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='02913804-404d-4851-950c-332dab3cd271', max_length=100),
        ),
    ]
