# Generated by Django 5.1 on 2024-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='8f9a756d-89ab-4d10-9dc9-53346bd191b9', max_length=100),
        ),
    ]
