# Generated by Django 5.1 on 2024-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='22233f86-8ec0-47a3-a221-9a7fa2b1fb8a', max_length=100),
        ),
    ]
