# Generated by Django 5.1 on 2024-10-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='0775b870-b3d7-401c-a89c-effaac55f2aa', max_length=100),
        ),
    ]
