# Generated by Django 5.1 on 2024-10-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='4dccec73-58f6-42a5-a74b-c47c8fa6bc19', max_length=100),
        ),
    ]
