# Generated by Django 5.1 on 2024-10-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='1ce7cfe1-fc91-46dc-ac4a-09db2ae15fa1', max_length=100),
        ),
    ]
