# Generated by Django 5.1 on 2024-10-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='d6fce3ba-5fc0-4534-b466-6465d1f32d93', max_length=100),
        ),
    ]
