# Generated by Django 5.1 on 2024-11-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='9bd6248a-19ee-4425-a68e-a0a653e15a31', max_length=100),
        ),
    ]
