# Generated by Django 5.1 on 2024-09-26 03:59

import developer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_detail', models.CharField(max_length=30)),
                ('task_detail_video', models.FileField(blank=True, null=True, upload_to='task/task_detail_video', validators=[developer.models.validate_file_size])),
                ('requirement_document', models.FileField(upload_to='task_requirement_document', validators=[developer.models.validate_file_size])),
                ('task_timeline', models.CharField(max_length=30)),
                ('task_cost', models.IntegerField()),
                ('instruction_video', models.FileField(blank=True, null=True, upload_to='task/instruction_video', validators=[developer.models.validate_file_size])),
                ('code_explanation_video', models.FileField(blank=True, null=True, upload_to='task/code_explanation_video', validators=[developer.models.validate_file_size])),
                ('lastest_files', models.FileField(blank=True, null=True, upload_to='task/code_explanation_video', validators=[developer.models.validate_file_size])),
                ('status', models.CharField(choices=[('open', 'Open'), ('started', 'Started'), ('completed', 'Completed')], default='open', max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=30, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.project')),
            ],
        ),
    ]
