# Generated by Django 5.1 on 2024-10-02 08:43

import developer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_alter_task_requirement_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='requirement_document',
            field=models.FileField(blank=True, null=True, upload_to='task_requirement_document', validators=[developer.models.validate_file_size]),
        ),
    ]
