# Generated by Django 5.1 on 2024-09-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_userprofile_user'),
        ('dashboard', '0002_alter_subscription_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.userprofile'),
        ),
    ]
