# Generated by Django 5.1 on 2024-09-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_subscription_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='chat',
            new_name='bot',
        ),
    ]
