# Generated by Django 5.1 on 2024-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_chat_subscription_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cancelled',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
