# Generated by Django 5.1 on 2024-09-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_subscription_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
