# Generated by Django 5.1 on 2024-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_subscription_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_id',
            field=models.CharField(max_length=255),
        ),
    ]
