# Generated by Django 5.1 on 2024-09-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='chat_id',
            new_name='bot_id',
        ),
    ]
