# Generated by Django 5.1 on 2024-09-15 03:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_rename_chat_id_userprofile_bot_id'),
        ('dashboard', '0004_rename_chat_subscription_bot'),
        ('product_dashboard', '0012_rename_chat_order_bot_rename_chat_product_bot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Bot',
        ),
    ]
