# Generated by Django 5.1 on 2024-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_rename_userprofile_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_father_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='telegram_username',
            field=models.CharField(max_length=50),
        ),
    ]
