# Generated by Django 5.1 on 2024-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_bot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='database_backup',
            field=models.FileField(default='t', upload_to='backup'),
            preserve_default=False,
        ),
    ]
