# Generated by Django 5.1 on 2024-09-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_bot_database_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='database_backup',
            field=models.FileField(blank=True, upload_to='backup'),
        ),
    ]
