# Generated by Django 5.1 on 2024-10-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_bot_database_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='type',
            field=models.CharField(default='subscription', max_length=50),
            preserve_default=False,
        ),
    ]
