# Generated by Django 5.1 on 2024-10-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_bot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='database_backup',
            field=models.FileField(blank=True, null=True, upload_to='backup'),
        ),
    ]
