# Generated by Django 5.1 on 2024-09-16 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('file', models.ImageField(upload_to='', verbose_name='instagram_imgs')),
                ('post_url', models.URLField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 9, 16, 14, 45, 27, 792766))),
            ],
        ),
    ]
