# Generated by Django 5.1 on 2024-09-27 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_alter_instagrampost_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgptprompt',
            old_name='propmt',
            new_name='prompt',
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 5, 57, 3, 434123)),
        ),
    ]
