# Generated by Django 5.1 on 2024-10-10 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0028_alter_instagrampost_date_time_instagrapostwaitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 11, 51, 23, 5969)),
        ),
    ]
