# Generated by Django 5.1 on 2024-10-10 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0029_alter_instagrampost_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsession',
            name='proxy',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 12, 11, 9, 716899)),
        ),
    ]
