# Generated by Django 5.1 on 2024-10-10 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0030_instagramsession_proxy_alter_instagrampost_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 13, 3, 58, 581381)),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='file',
            field=models.ImageField(upload_to='', verbose_name='instagram_imgs/'),
        ),
        migrations.AlterField(
            model_name='instagrapostwaitlist',
            name='file',
            field=models.ImageField(upload_to='', verbose_name='instagram_imgs/'),
        ),
    ]
