# Generated by Django 5.1 on 2024-10-10 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0031_alter_instagrampost_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrapostwaitlist',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 19, 40, 53, 165348)),
        ),
    ]
