# Generated by Django 5.1 on 2024-10-11 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0032_instagrapostwaitlist_task_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostWithProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('error', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 4, 39, 23, 163392)),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='file',
            field=models.ImageField(upload_to='instagram_imgs'),
        ),
        migrations.AlterField(
            model_name='instagrapostwaitlist',
            name='file',
            field=models.ImageField(upload_to='instagram_imgs'),
        ),
    ]
