# Generated by Django 5.1 on 2024-11-04 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0033_postwithproblem_alter_instagrampost_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='caption',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 16, 26, 19, 552267)),
        ),
        migrations.AlterField(
            model_name='instagrapostwaitlist',
            name='caption',
            field=models.CharField(max_length=1000),
        ),
    ]
