# Generated by Django 5.1 on 2024-09-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_alter_userprofile_telegram_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered')], max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('payment', models.CharField(choices=[('paypal', 'paypal'), ('stripe', 'stripe'), ('crypto', 'crypto')], max_length=15)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mail_service', models.CharField(max_length=255)),
                ('discount_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('thumbnail', models.FileField(blank=True, upload_to='products/thumnail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_img', models.FileField(upload_to='products/imgs')),
                ('product_category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_dashboard.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_dashboard.product')),
            ],
        ),
    ]
