# Generated by Django 5.1 on 2024-09-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
