# Generated by Django 5.1 on 2024-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_dashboard', '0003_alter_product_product_img_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
