# Generated by Django 5.1 on 2024-09-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_userprofile_telegram_username'),
        ('product_dashboard', '0004_alter_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chat',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='auth_app.userprofile'),
            preserve_default=False,
        ),
    ]
