# Generated by Django 5.1 on 2024-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_dashboard', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='products/thumbnail'),
        ),
    ]
