# Generated by Django 5.1 on 2024-09-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_dashboard', '0011_productdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='chat',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='chat',
            new_name='bot',
        ),
    ]
