# Generated by Django 5.1 on 2024-09-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_dashboard', '0013_product_brand_alter_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
    ]
